exp_dir: "/Users/honghsilee/Documents/GitHub/dldegibbs/trained_models/res_256_to_100"

train_data:
  train_data_dir: "/gpfs/data/cbi/shared/unpacked_imagenet/"
  test_data_dir: "/gpfs/data/cbi/shared/unpacked_imagenet/2019_04_12_imagenet2013test"
  workers_per_gpu: 10
